#DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(id SERIAL NOT NULL PRIMARY KEY, username VARCHAR(64) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255), avatar BLOB);

DROP TABLE IF EXISTS games;
CREATE TABLE IF NOT EXISTS games(id serial NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL, logo BLOB);

#DROP TABLE IF EXISTS scores;
CREATE TABLE IF NOT EXISTS scores(id SERIAL NOT NULL PRIMARY KEY, userid INT NOT NULL, game INT(4) NOT NULL, score INT NOT NULL, date DATETIME NOT NULL);

DROP TABLE IF EXISTS roles;
CREATE TABLE IF NOT EXISTS roles(id SERIAL NOT NULL PRIMARY KEY,roleid INT NOT NULL REFERENCES role_types.roleid,userid INT NOT NULL REFERENCES users.id);

DROP TABLE IF EXISTS role_types;
CREATE TABLE IF NOT EXISTS role_types(roleid SERIAL NOT NULL PRIMARY KEY, title VARCHAR(64) NOT NULL, description VARCHAR(255) NOT NULL);